ERROR    celery.backends.redis:redis.py:363 Connection to Redis lost: Retry (0/20) now.
ERROR    celery.backends.redis:redis.py:363 Connection to Redis lost: Retry (1/20) in 1.00 second.
ERROR    celery.backends.redis:redis.py:363 Connection to Redis lost: Retry (2/20) in 1.00 second.
ERROR    celery.backends.redis:redis.py:363 Connection to Redis lost: Retry (3/20) in 1.00 second.
ERROR    celery.backends.redis:redis.py:363 Connection to Redis lost: Retry (4/20) in 1.00 second.
ERROR    celery.backends.redis:redis.py:363 Connection to Redis lost: Retry (5/20) in 1.00 second.
ERROR    celery.backends.redis:redis.py:363 Connection to Redis lost: Retry (6/20) in 1.00 second.
ERROR    celery.backends.redis:redis.py:363 Connection to Redis lost: Retry (7/20) in 1.00 second.
ERROR    celery.backends.redis:redis.py:363 Connection to Redis lost: Retry (8/20) in 1.00 second.
ERROR    celery.backends.redis:redis.py:363 Connection to Redis lost: Retry (9/20) in 1.00 second.
ERROR    celery.backends.redis:redis.py:363 Connection to Redis lost: Retry (10/20) in 1.00 second.
ERROR    celery.backends.redis:redis.py:363 Connection to Redis lost: Retry (11/20) in 1.00 second.
ERROR    celery.backends.redis:redis.py:363 Connection to Redis lost: Retry (12/20) in 1.00 second.
ERROR    celery.backends.redis:redis.py:363 Connection to Redis lost: Retry (13/20) in 1.00 second.
ERROR    celery.backends.redis:redis.py:363 Connection to Redis lost: Retry (14/20) in 1.00 second.
ERROR    celery.backends.redis:redis.py:363 Connection to Redis lost: Retry (15/20) in 1.00 second.
ERROR    celery.backends.redis:redis.py:363 Connection to Redis lost: Retry (16/20) in 1.00 second.
ERROR    celery.backends.redis:redis.py:363 Connection to Redis lost: Retry (17/20) in 1.00 second.
ERROR    celery.backends.redis:redis.py:363 Connection to Redis lost: Retry (18/20) in 1.00 second.
ERROR    celery.backends.redis:redis.py:363 Connection to Redis lost: Retry (19/20) in 1.00 second.
CRITICAL celery.backends.redis:redis.py:122 
Retry limit exceeded while trying to reconnect to the Celery redis result store backend. The Celery application must be restarted.